### ISSUE TITLE
http.client.RemoteDisconnected: Remote end closed connection without response

### ISSUE THREAD

**Issue by hopesala** [python-astrodynamics/spacetrack#53]
Traceback (most recent call last):
  File "D:\anaconda3\envs\python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "D:\anaconda3\envs\python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\anaconda3\envs\python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "D:\anaconda3\envs\python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "D:\anaconda3\envs\python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "D:\anaconda3\envs\python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda3\envs\python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\anaconda3\envs\python38\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "D:\anaconda3\envs\python38\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\anaconda3\envs\python38\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "D:\anaconda3\envs\python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "D:\anaconda3\envs\python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\anaconda3\envs\python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "D:\anaconda3\envs\python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "D:\anaconda3\envs\python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "D:\anaconda3\envs\python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Users/123/PycharmProjects/Honghua/tle_auto_download_from_space_track.py", line 65, in <module>
    lines = st.tle_publish(norad_cat_id=[v], iter_lines=True, publish_epoch=drange, orderby='TLE_LINE1', format='tle') # epoch ->publish_epoch
  File "D:\anaconda3\envs\python38\lib\site-packages\spacetrack\base.py", line 409, in generic_request
    resp = self._ratelimited_get(url, stream=iter_lines or iter_content)
  File "D:\anaconda3\envs\python38\lib\site-packages\spacetrack\base.py", line 467, in _ratelimited_get
    resp = self.session.get(*args, **kwargs)
  File "D:\anaconda3\envs\python38\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "D:\anaconda3\envs\python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda3\envs\python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda3\envs\python38\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by RazerM** [comment]
This is not a bug, see the error message
